== Conventions

In this section we will describe hash functions in a general way.

Each hash function has its own capabilities and slightly different parameters.
If you wish to make use of those special features then you will need to create wrappers to specific implementations.
Fortunately those wrappers are cheap in Nim--they are likely to be inlined away and you will pay very little or not at all.

=== Seeds and Keys

Some hashing algorithms have a concept of _keys_ or _seeds_.
This is a piece of secondary information you can use to alter the result of a hash algorithm.

There is no generic way to handle these.
Some algorithms like the Blake and XXHash family allow taking salt or a seed as a separate parameter.
Some algorithms do not support this at all--you have to rely on HMAC or some other salting mechanism.

=== One-shot APIs

A one-shot API consumes an entire buffer, calculates a hash, and outputs that hash in a single function call.
These are based on the following function signature:

[source,nim]
----
OneShotHash* = proc(
  output, input: pointer;
  out_len, in_len: int) {.nimcall.}
----

=== Streaming APIs

Streaming APIs consist of multiple distinct steps:

. Initializing the stream kernel
. Feeding data on a piece-by-piece basis
. Finalization; telling a stream kernel there is no more data to process and extracting the actual hash

As of 20231107 this is now based on a [type concept](https://nim-lang.org/docs/manual_experimental.html#concepts):

[source,nim]
----
StreamingHash* = concept var x
  # Prepares the hasher for streaming.
  init(x)
  # Pushes some amount of bytes in to the device.
  update(x, pointer, int)
  # Finish the job and output the bytes
  final(x, pointer, int)
----
